service: fontys-auth
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3

automatic_scaling:
  max_num_instances: 1
resources:
  cpu: .5
  memory_gb: 0.5
  disk_size_gb: 10